package com.lanmao.data.sync.db.oracle.entity;

import java.util.Date;

public class AuthOrderEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.ID
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.SUBJECT_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String subjectNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.STATUS
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.INITIATOR
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String initiator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.REQUEST_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String requestNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.AUTH_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String authNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.CARD_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.CARD_HOLDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String cardHolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.CRED_NUM
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String credNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.MOBILE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.MERCHANT_ORDER_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String merchantOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.CREATE_TIME
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.COMPLETE_TIME
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private Date completeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.BANK
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.AUTH_FACTOR
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String authFactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.CNAPS
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String cnaps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.AUTH_MODE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String authMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.BIZ_TYPE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String bizType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.MERCHANT_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String merchantNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.AUTH_CHANNEL
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String authChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.PLATFORM
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.ERROR_CODE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String errorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.ERROR_MESSAGE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String errorMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.TRANSLATE_ERROR_CODE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String translateErrorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.TRANSLATE_ERROR_MESSAGE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private String translateErrorMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_AUTH_ORDER.CONSUME_TIME
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    private Short consumeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.ID
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.ID
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.ID
     *
     * @param id the value for LM_PAY.T_AUTH_ORDER.ID
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.SUBJECT_NO
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.SUBJECT_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getSubjectNo() {
        return subjectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.SUBJECT_NO
     *
     * @param subjectNo the value for LM_PAY.T_AUTH_ORDER.SUBJECT_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setSubjectNo(String subjectNo) {
        this.subjectNo = subjectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.STATUS
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.STATUS
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.STATUS
     *
     * @param status the value for LM_PAY.T_AUTH_ORDER.STATUS
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.INITIATOR
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.INITIATOR
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getInitiator() {
        return initiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.INITIATOR
     *
     * @param initiator the value for LM_PAY.T_AUTH_ORDER.INITIATOR
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setInitiator(String initiator) {
        this.initiator = initiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.REQUEST_NO
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.REQUEST_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getRequestNo() {
        return requestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.REQUEST_NO
     *
     * @param requestNo the value for LM_PAY.T_AUTH_ORDER.REQUEST_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setRequestNo(String requestNo) {
        this.requestNo = requestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.AUTH_NO
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.AUTH_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getAuthNo() {
        return authNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.AUTH_NO
     *
     * @param authNo the value for LM_PAY.T_AUTH_ORDER.AUTH_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setAuthNo(String authNo) {
        this.authNo = authNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.CARD_NO
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.CARD_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.CARD_NO
     *
     * @param cardNo the value for LM_PAY.T_AUTH_ORDER.CARD_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.CARD_HOLDER
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.CARD_HOLDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getCardHolder() {
        return cardHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.CARD_HOLDER
     *
     * @param cardHolder the value for LM_PAY.T_AUTH_ORDER.CARD_HOLDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setCardHolder(String cardHolder) {
        this.cardHolder = cardHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.CRED_NUM
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.CRED_NUM
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getCredNum() {
        return credNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.CRED_NUM
     *
     * @param credNum the value for LM_PAY.T_AUTH_ORDER.CRED_NUM
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setCredNum(String credNum) {
        this.credNum = credNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.MOBILE
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.MOBILE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.MOBILE
     *
     * @param mobile the value for LM_PAY.T_AUTH_ORDER.MOBILE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.MERCHANT_ORDER_NO
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.MERCHANT_ORDER_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getMerchantOrderNo() {
        return merchantOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.MERCHANT_ORDER_NO
     *
     * @param merchantOrderNo the value for LM_PAY.T_AUTH_ORDER.MERCHANT_ORDER_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setMerchantOrderNo(String merchantOrderNo) {
        this.merchantOrderNo = merchantOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.CREATE_TIME
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.CREATE_TIME
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.CREATE_TIME
     *
     * @param createTime the value for LM_PAY.T_AUTH_ORDER.CREATE_TIME
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.COMPLETE_TIME
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.COMPLETE_TIME
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.COMPLETE_TIME
     *
     * @param completeTime the value for LM_PAY.T_AUTH_ORDER.COMPLETE_TIME
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.BANK
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.BANK
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.BANK
     *
     * @param bank the value for LM_PAY.T_AUTH_ORDER.BANK
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setBank(String bank) {
        this.bank = bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.AUTH_FACTOR
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.AUTH_FACTOR
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getAuthFactor() {
        return authFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.AUTH_FACTOR
     *
     * @param authFactor the value for LM_PAY.T_AUTH_ORDER.AUTH_FACTOR
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setAuthFactor(String authFactor) {
        this.authFactor = authFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.CNAPS
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.CNAPS
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getCnaps() {
        return cnaps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.CNAPS
     *
     * @param cnaps the value for LM_PAY.T_AUTH_ORDER.CNAPS
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setCnaps(String cnaps) {
        this.cnaps = cnaps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.AUTH_MODE
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.AUTH_MODE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getAuthMode() {
        return authMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.AUTH_MODE
     *
     * @param authMode the value for LM_PAY.T_AUTH_ORDER.AUTH_MODE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setAuthMode(String authMode) {
        this.authMode = authMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.BIZ_TYPE
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.BIZ_TYPE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.BIZ_TYPE
     *
     * @param bizType the value for LM_PAY.T_AUTH_ORDER.BIZ_TYPE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setBizType(String bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.MERCHANT_NO
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.MERCHANT_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.MERCHANT_NO
     *
     * @param merchantNo the value for LM_PAY.T_AUTH_ORDER.MERCHANT_NO
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.AUTH_CHANNEL
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.AUTH_CHANNEL
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getAuthChannel() {
        return authChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.AUTH_CHANNEL
     *
     * @param authChannel the value for LM_PAY.T_AUTH_ORDER.AUTH_CHANNEL
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setAuthChannel(String authChannel) {
        this.authChannel = authChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.PLATFORM
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.PLATFORM
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.PLATFORM
     *
     * @param platform the value for LM_PAY.T_AUTH_ORDER.PLATFORM
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.ERROR_CODE
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.ERROR_CODE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.ERROR_CODE
     *
     * @param errorCode the value for LM_PAY.T_AUTH_ORDER.ERROR_CODE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.ERROR_MESSAGE
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.ERROR_MESSAGE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.ERROR_MESSAGE
     *
     * @param errorMessage the value for LM_PAY.T_AUTH_ORDER.ERROR_MESSAGE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.TRANSLATE_ERROR_CODE
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.TRANSLATE_ERROR_CODE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getTranslateErrorCode() {
        return translateErrorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.TRANSLATE_ERROR_CODE
     *
     * @param translateErrorCode the value for LM_PAY.T_AUTH_ORDER.TRANSLATE_ERROR_CODE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setTranslateErrorCode(String translateErrorCode) {
        this.translateErrorCode = translateErrorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.TRANSLATE_ERROR_MESSAGE
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.TRANSLATE_ERROR_MESSAGE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public String getTranslateErrorMessage() {
        return translateErrorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.TRANSLATE_ERROR_MESSAGE
     *
     * @param translateErrorMessage the value for LM_PAY.T_AUTH_ORDER.TRANSLATE_ERROR_MESSAGE
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setTranslateErrorMessage(String translateErrorMessage) {
        this.translateErrorMessage = translateErrorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_AUTH_ORDER.CONSUME_TIME
     *
     * @return the value of LM_PAY.T_AUTH_ORDER.CONSUME_TIME
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public Short getConsumeTime() {
        return consumeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_AUTH_ORDER.CONSUME_TIME
     *
     * @param consumeTime the value for LM_PAY.T_AUTH_ORDER.CONSUME_TIME
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    public void setConsumeTime(Short consumeTime) {
        this.consumeTime = consumeTime;
    }
}