package com.lanmao.data.sync.db.db2.dao;

import com.lanmao.data.sync.db.db2.entity.AuthOrderEntity;
import com.lanmao.data.sync.db.db2.entity.AuthOrderEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthOrderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    long countByExample(AuthOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    int deleteByExample(AuthOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    int insert(AuthOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    int insertSelective(AuthOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    List<AuthOrderEntity> selectByExample(AuthOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    AuthOrderEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") AuthOrderEntity record, @Param("example") AuthOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    int updateByExample(@Param("record") AuthOrderEntity record, @Param("example") AuthOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    int updateByPrimaryKeySelective(AuthOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER
     *
     * @mbg.generated Mon Mar 05 18:15:11 CST 2018
     */
    int updateByPrimaryKey(AuthOrderEntity record);
}