package com.lanmao.data.sync.dao.oracle;

import java.util.List;

import com.lanmao.data.sync.dao.entity.AuthOrderCountEntity;
import com.lanmao.data.sync.dao.entity.AuthOrderCountEntityExample;
import org.apache.ibatis.annotations.Param;

public interface AuthOrderCountEntityMapper extends SaveDataMapper<AuthOrderCountEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER_COUNT
     *
     * @mbggenerated Tue Oct 24 10:46:06 CST 2017
     */
    int countByExample(AuthOrderCountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER_COUNT
     *
     * @mbggenerated Tue Oct 24 10:46:06 CST 2017
     */
    int deleteByExample(AuthOrderCountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER_COUNT
     *
     * @mbggenerated Tue Oct 24 10:46:06 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER_COUNT
     *
     * @mbggenerated Tue Oct 24 10:46:06 CST 2017
     */
    int insert(AuthOrderCountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER_COUNT
     *
     * @mbggenerated Tue Oct 24 10:46:06 CST 2017
     */
    int insertSelective(AuthOrderCountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER_COUNT
     *
     * @mbggenerated Tue Oct 24 10:46:06 CST 2017
     */
    List<AuthOrderCountEntity> selectByExample(AuthOrderCountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER_COUNT
     *
     * @mbggenerated Tue Oct 24 10:46:06 CST 2017
     */
    AuthOrderCountEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER_COUNT
     *
     * @mbggenerated Tue Oct 24 10:46:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") AuthOrderCountEntity record, @Param("example") AuthOrderCountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER_COUNT
     *
     * @mbggenerated Tue Oct 24 10:46:06 CST 2017
     */
    int updateByExample(@Param("record") AuthOrderCountEntity record, @Param("example") AuthOrderCountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER_COUNT
     *
     * @mbggenerated Tue Oct 24 10:46:06 CST 2017
     */
    int updateByPrimaryKeySelective(AuthOrderCountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ORDER_COUNT
     *
     * @mbggenerated Tue Oct 24 10:46:06 CST 2017
     */
    int updateByPrimaryKey(AuthOrderCountEntity record);
    
    void batchInsert(List<AuthOrderCountEntity> record);
}