package com.lanmao.data.sync.dao.oracle;

import java.util.List;

import com.lanmao.data.sync.dao.entity.AuthRiskControlEntity;
import com.lanmao.data.sync.dao.entity.AuthRiskControlEntityExample;
import org.apache.ibatis.annotations.Param;

public interface AuthRiskControlEntityMapper extends SaveDataMapper<AuthRiskControlEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_RISK_CONTROL
     *
     * @mbggenerated Sat Oct 14 15:35:38 CST 2017
     */
    int countByExample(AuthRiskControlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_RISK_CONTROL
     *
     * @mbggenerated Sat Oct 14 15:35:38 CST 2017
     */
    int deleteByExample(AuthRiskControlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_RISK_CONTROL
     *
     * @mbggenerated Sat Oct 14 15:35:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_RISK_CONTROL
     *
     * @mbggenerated Sat Oct 14 15:35:38 CST 2017
     */
    int insert(AuthRiskControlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_RISK_CONTROL
     *
     * @mbggenerated Sat Oct 14 15:35:38 CST 2017
     */
    int insertSelective(AuthRiskControlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_RISK_CONTROL
     *
     * @mbggenerated Sat Oct 14 15:35:38 CST 2017
     */
    List<AuthRiskControlEntity> selectByExample(AuthRiskControlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_RISK_CONTROL
     *
     * @mbggenerated Sat Oct 14 15:35:38 CST 2017
     */
    AuthRiskControlEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_RISK_CONTROL
     *
     * @mbggenerated Sat Oct 14 15:35:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") AuthRiskControlEntity record, @Param("example") AuthRiskControlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_RISK_CONTROL
     *
     * @mbggenerated Sat Oct 14 15:35:38 CST 2017
     */
    int updateByExample(@Param("record") AuthRiskControlEntity record, @Param("example") AuthRiskControlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_RISK_CONTROL
     *
     * @mbggenerated Sat Oct 14 15:35:38 CST 2017
     */
    int updateByPrimaryKeySelective(AuthRiskControlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_RISK_CONTROL
     *
     * @mbggenerated Sat Oct 14 15:35:38 CST 2017
     */
    int updateByPrimaryKey(AuthRiskControlEntity record);
}