package com.lanmao.data.sync.dao.oracle;

import java.util.List;

import com.lanmao.data.sync.dao.entity.AuthAuthorizationEntity;
import com.lanmao.data.sync.dao.entity.AuthAuthorizationEntityExample;
import org.apache.ibatis.annotations.Param;

public interface AuthAuthorizationEntityMapper extends SaveDataMapper<AuthAuthorizationEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 14:00:23 CST 2016
     */
    int countByExample(AuthAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 14:00:23 CST 2016
     */
    int deleteByExample(AuthAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 14:00:23 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 14:00:23 CST 2016
     */
    int insert(AuthAuthorizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 14:00:23 CST 2016
     */
    int insertSelective(AuthAuthorizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 14:00:23 CST 2016
     */
    List<AuthAuthorizationEntity> selectByExample(AuthAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 14:00:23 CST 2016
     */
    AuthAuthorizationEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 14:00:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") AuthAuthorizationEntity record, @Param("example") AuthAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 14:00:23 CST 2016
     */
    int updateByExample(@Param("record") AuthAuthorizationEntity record, @Param("example") AuthAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 14:00:23 CST 2016
     */
    int updateByPrimaryKeySelective(AuthAuthorizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 14:00:23 CST 2016
     */
    int updateByPrimaryKey(AuthAuthorizationEntity record);
}