package com.lanmao.data.sync.dao.oracle;

import java.util.List;

import com.lanmao.data.sync.dao.entity.AuthBankRouterEntity;
import com.lanmao.data.sync.dao.entity.AuthBankRouterEntityExample;
import org.apache.ibatis.annotations.Param;

public interface AuthBankRouterEntityMapper extends SaveDataMapper<AuthBankRouterEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_BANK_ROUTER
     *
     * @mbggenerated Mon Jul 10 18:22:35 CST 2017
     */
    int countByExample(AuthBankRouterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_BANK_ROUTER
     *
     * @mbggenerated Mon Jul 10 18:22:35 CST 2017
     */
    int deleteByExample(AuthBankRouterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_BANK_ROUTER
     *
     * @mbggenerated Mon Jul 10 18:22:35 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_BANK_ROUTER
     *
     * @mbggenerated Mon Jul 10 18:22:35 CST 2017
     */
    int insert(AuthBankRouterEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_BANK_ROUTER
     *
     * @mbggenerated Mon Jul 10 18:22:35 CST 2017
     */
    int insertSelective(AuthBankRouterEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_BANK_ROUTER
     *
     * @mbggenerated Mon Jul 10 18:22:35 CST 2017
     */
    List<AuthBankRouterEntity> selectByExample(AuthBankRouterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_BANK_ROUTER
     *
     * @mbggenerated Mon Jul 10 18:22:35 CST 2017
     */
    AuthBankRouterEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_BANK_ROUTER
     *
     * @mbggenerated Mon Jul 10 18:22:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") AuthBankRouterEntity record, @Param("example") AuthBankRouterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_BANK_ROUTER
     *
     * @mbggenerated Mon Jul 10 18:22:35 CST 2017
     */
    int updateByExample(@Param("record") AuthBankRouterEntity record, @Param("example") AuthBankRouterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_BANK_ROUTER
     *
     * @mbggenerated Mon Jul 10 18:22:35 CST 2017
     */
    int updateByPrimaryKeySelective(AuthBankRouterEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_BANK_ROUTER
     *
     * @mbggenerated Mon Jul 10 18:22:35 CST 2017
     */
    int updateByPrimaryKey(AuthBankRouterEntity record);
}