package com.lanmao.data.sync.dao.oracle;

import java.util.List;

import com.lanmao.data.sync.dao.entity.AuthBankRouterEntity;
import com.lanmao.data.sync.dao.entity.AuthChannelConfigEntity;
import com.lanmao.data.sync.dao.entity.AuthChannelConfigEntityExample;
import org.apache.ibatis.annotations.Param;

public interface AuthChannelConfigEntityMapper extends SaveDataMapper<AuthChannelConfigEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    int countByExample(AuthChannelConfigEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    int deleteByExample(AuthChannelConfigEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    int insert(AuthChannelConfigEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    int insertSelective(AuthChannelConfigEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    List<AuthChannelConfigEntity> selectByExampleWithBLOBs(AuthChannelConfigEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    List<AuthChannelConfigEntity> selectByExample(AuthChannelConfigEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    AuthChannelConfigEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") AuthChannelConfigEntity record, @Param("example") AuthChannelConfigEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") AuthChannelConfigEntity record, @Param("example") AuthChannelConfigEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    int updateByExample(@Param("record") AuthChannelConfigEntity record, @Param("example") AuthChannelConfigEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    int updateByPrimaryKeySelective(AuthChannelConfigEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(AuthChannelConfigEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 23 17:30:48 CST 2016
     */
    int updateByPrimaryKey(AuthChannelConfigEntity record);
}