package com.lanmao.data.sync.dao.oracle;

import java.util.List;
import java.util.Map;

import com.lanmao.data.sync.dao.entity.PaymentEntity;
import com.lanmao.data.sync.dao.entity.PaymentEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PaymentEntityMapper extends SaveDataMapper<PaymentEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT
     *
     * @mbggenerated Tue Jan 16 10:07:26 CST 2018
     */
    int countByExample(PaymentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT
     *
     * @mbggenerated Tue Jan 16 10:07:26 CST 2018
     */
    int deleteByExample(PaymentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT
     *
     * @mbggenerated Tue Jan 16 10:07:26 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT
     *
     * @mbggenerated Tue Jan 16 10:07:26 CST 2018
     */
    int insert(PaymentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT
     *
     * @mbggenerated Tue Jan 16 10:07:26 CST 2018
     */
    int insertSelective(PaymentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT
     *
     * @mbggenerated Tue Jan 16 10:07:26 CST 2018
     */
    List<PaymentEntity> selectByExample(PaymentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT
     *
     * @mbggenerated Tue Jan 16 10:07:26 CST 2018
     */
    PaymentEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT
     *
     * @mbggenerated Tue Jan 16 10:07:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") PaymentEntity record, @Param("example") PaymentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT
     *
     * @mbggenerated Tue Jan 16 10:07:26 CST 2018
     */
    int updateByExample(@Param("record") PaymentEntity record, @Param("example") PaymentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT
     *
     * @mbggenerated Tue Jan 16 10:07:26 CST 2018
     */
    int updateByPrimaryKeySelective(PaymentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT
     *
     * @mbggenerated Tue Jan 16 10:07:26 CST 2018
     */
    int updateByPrimaryKey(PaymentEntity record);

    List<PaymentEntity> queryToCloseOrder();

    List<PaymentEntity> queryToUnCheckedPayment();

    List<Map<String,Long>> queryToSupplementOrder(@Param("payWay") String payWay, @Param("startTime") String startTime, @Param("endTime") String endTime);
}