package com.lanmao.data.sync.dao.oracle;

import java.util.List;

import com.lanmao.data.sync.dao.entity.PaymentCashreserveAccntEntity;
import com.lanmao.data.sync.dao.entity.PaymentCashreserveAccntEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PaymentCashreserveAccntEntityMapper extends SaveDataMapper<PaymentCashreserveAccntEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CASHRESERVE_ACCNT
     *
     * @mbggenerated Fri Dec 02 16:18:11 CST 2016
     */
    int countByExample(PaymentCashreserveAccntEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CASHRESERVE_ACCNT
     *
     * @mbggenerated Fri Dec 02 16:18:11 CST 2016
     */
    int deleteByExample(PaymentCashreserveAccntEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CASHRESERVE_ACCNT
     *
     * @mbggenerated Fri Dec 02 16:18:11 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CASHRESERVE_ACCNT
     *
     * @mbggenerated Fri Dec 02 16:18:11 CST 2016
     */
    int insert(PaymentCashreserveAccntEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CASHRESERVE_ACCNT
     *
     * @mbggenerated Fri Dec 02 16:18:11 CST 2016
     */
    int insertSelective(PaymentCashreserveAccntEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CASHRESERVE_ACCNT
     *
     * @mbggenerated Fri Dec 02 16:18:11 CST 2016
     */
    List<PaymentCashreserveAccntEntity> selectByExample(PaymentCashreserveAccntEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CASHRESERVE_ACCNT
     *
     * @mbggenerated Fri Dec 02 16:18:11 CST 2016
     */
    PaymentCashreserveAccntEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CASHRESERVE_ACCNT
     *
     * @mbggenerated Fri Dec 02 16:18:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") PaymentCashreserveAccntEntity record, @Param("example") PaymentCashreserveAccntEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CASHRESERVE_ACCNT
     *
     * @mbggenerated Fri Dec 02 16:18:11 CST 2016
     */
    int updateByExample(@Param("record") PaymentCashreserveAccntEntity record, @Param("example") PaymentCashreserveAccntEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CASHRESERVE_ACCNT
     *
     * @mbggenerated Fri Dec 02 16:18:11 CST 2016
     */
    int updateByPrimaryKeySelective(PaymentCashreserveAccntEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CASHRESERVE_ACCNT
     *
     * @mbggenerated Fri Dec 02 16:18:11 CST 2016
     */
    int updateByPrimaryKey(PaymentCashreserveAccntEntity record);
}