package com.lanmao.data.sync.dao.oracle;

import java.util.List;

import com.lanmao.data.sync.dao.entity.PaymentRouterRuleEntryEntity;
import com.lanmao.data.sync.dao.entity.PaymentRouteRuleEntryEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PaymentRouterRuleEntryEntityMapper extends SaveDataMapper<PaymentRouterRuleEntryEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_ENTRY
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int countByExample(PaymentRouteRuleEntryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_ENTRY
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int deleteByExample(PaymentRouteRuleEntryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_ENTRY
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_ENTRY
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int insert(PaymentRouterRuleEntryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_ENTRY
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int insertSelective(PaymentRouterRuleEntryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_ENTRY
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    List<PaymentRouterRuleEntryEntity> selectByExample(PaymentRouteRuleEntryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_ENTRY
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    PaymentRouterRuleEntryEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_ENTRY
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") PaymentRouterRuleEntryEntity record, @Param("example") PaymentRouteRuleEntryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_ENTRY
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int updateByExample(@Param("record") PaymentRouterRuleEntryEntity record, @Param("example") PaymentRouteRuleEntryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_ENTRY
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int updateByPrimaryKeySelective(PaymentRouterRuleEntryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_ENTRY
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int updateByPrimaryKey(PaymentRouterRuleEntryEntity record);
}