package com.lanmao.data.sync.dao.oracle;

import java.util.List;

import com.lanmao.data.sync.dao.entity.PaymentOrderExtendEntity;
import com.lanmao.data.sync.dao.entity.PaymentOrderExtendEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PaymentOrderExtendEntityMapper extends SaveDataMapper<PaymentOrderExtendEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    int countByExample(PaymentOrderExtendEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    int deleteByExample(PaymentOrderExtendEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    int insert(PaymentOrderExtendEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    int insertSelective(PaymentOrderExtendEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    List<PaymentOrderExtendEntity> selectByExampleWithBLOBs(PaymentOrderExtendEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    List<PaymentOrderExtendEntity> selectByExample(PaymentOrderExtendEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    PaymentOrderExtendEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") PaymentOrderExtendEntity record, @Param("example") PaymentOrderExtendEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") PaymentOrderExtendEntity record, @Param("example") PaymentOrderExtendEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    int updateByExample(@Param("record") PaymentOrderExtendEntity record, @Param("example") PaymentOrderExtendEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    int updateByPrimaryKeySelective(PaymentOrderExtendEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(PaymentOrderExtendEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER_EXTEND
     *
     * @mbggenerated Wed Jul 13 11:33:39 CST 2016
     */
    int updateByPrimaryKey(PaymentOrderExtendEntity record);
}