package com.lanmao.data.sync.dao.oracle;

import java.util.List;

import com.lanmao.data.sync.dao.entity.PaymentProfitTempletEntity;
import com.lanmao.data.sync.dao.entity.PaymentProfitTempletEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PaymentProfitTempletEntityMapper extends SaveDataMapper<PaymentProfitTempletEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_TEMPLET
     *
     * @mbggenerated Wed Oct 18 11:49:36 CST 2017
     */
    int countByExample(PaymentProfitTempletEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_TEMPLET
     *
     * @mbggenerated Wed Oct 18 11:49:36 CST 2017
     */
    int deleteByExample(PaymentProfitTempletEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_TEMPLET
     *
     * @mbggenerated Wed Oct 18 11:49:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_TEMPLET
     *
     * @mbggenerated Wed Oct 18 11:49:36 CST 2017
     */
    int insert(PaymentProfitTempletEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_TEMPLET
     *
     * @mbggenerated Wed Oct 18 11:49:36 CST 2017
     */
    int insertSelective(PaymentProfitTempletEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_TEMPLET
     *
     * @mbggenerated Wed Oct 18 11:49:36 CST 2017
     */
    List<PaymentProfitTempletEntity> selectByExample(PaymentProfitTempletEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_TEMPLET
     *
     * @mbggenerated Wed Oct 18 11:49:36 CST 2017
     */
    PaymentProfitTempletEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_TEMPLET
     *
     * @mbggenerated Wed Oct 18 11:49:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") PaymentProfitTempletEntity record, @Param("example") PaymentProfitTempletEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_TEMPLET
     *
     * @mbggenerated Wed Oct 18 11:49:36 CST 2017
     */
    int updateByExample(@Param("record") PaymentProfitTempletEntity record, @Param("example") PaymentProfitTempletEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_TEMPLET
     *
     * @mbggenerated Wed Oct 18 11:49:36 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentProfitTempletEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_TEMPLET
     *
     * @mbggenerated Wed Oct 18 11:49:36 CST 2017
     */
    int updateByPrimaryKey(PaymentProfitTempletEntity record);
}