package com.lanmao.data.sync.dao.oracle;

import java.util.List;

import com.lanmao.data.sync.dao.entity.PaymentCodeRuleEntity;
import com.lanmao.data.sync.dao.entity.PaymentCodeRuleEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PaymentCodeRuleEntityMapper extends SaveDataMapper<PaymentCodeRuleEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CODE_RULE
     *
     * @mbggenerated Thu May 18 11:49:12 CST 2017
     */
    int countByExample(PaymentCodeRuleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CODE_RULE
     *
     * @mbggenerated Thu May 18 11:49:12 CST 2017
     */
    int deleteByExample(PaymentCodeRuleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CODE_RULE
     *
     * @mbggenerated Thu May 18 11:49:12 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CODE_RULE
     *
     * @mbggenerated Thu May 18 11:49:12 CST 2017
     */
    int insert(PaymentCodeRuleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CODE_RULE
     *
     * @mbggenerated Thu May 18 11:49:12 CST 2017
     */
    int insertSelective(PaymentCodeRuleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CODE_RULE
     *
     * @mbggenerated Thu May 18 11:49:12 CST 2017
     */
    List<PaymentCodeRuleEntity> selectByExample(PaymentCodeRuleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CODE_RULE
     *
     * @mbggenerated Thu May 18 11:49:12 CST 2017
     */
    PaymentCodeRuleEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CODE_RULE
     *
     * @mbggenerated Thu May 18 11:49:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") PaymentCodeRuleEntity record, @Param("example") PaymentCodeRuleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CODE_RULE
     *
     * @mbggenerated Thu May 18 11:49:12 CST 2017
     */
    int updateByExample(@Param("record") PaymentCodeRuleEntity record, @Param("example") PaymentCodeRuleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CODE_RULE
     *
     * @mbggenerated Thu May 18 11:49:12 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentCodeRuleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CODE_RULE
     *
     * @mbggenerated Thu May 18 11:49:12 CST 2017
     */
    int updateByPrimaryKey(PaymentCodeRuleEntity record);
}