package com.lanmao.data.sync.dao.oracle;

import java.util.List;

import com.lanmao.data.sync.dao.entity.PaymentErrorCodeEntity;
import com.lanmao.data.sync.dao.entity.PaymentErrorCodeEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PaymentErrorCodeEntityMapper extends SaveDataMapper<PaymentErrorCodeEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ERROR_CODE
     *
     * @mbggenerated Tue Sep 19 14:16:43 CST 2017
     */
    int countByExample(PaymentErrorCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ERROR_CODE
     *
     * @mbggenerated Tue Sep 19 14:16:43 CST 2017
     */
    int deleteByExample(PaymentErrorCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ERROR_CODE
     *
     * @mbggenerated Tue Sep 19 14:16:43 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ERROR_CODE
     *
     * @mbggenerated Tue Sep 19 14:16:43 CST 2017
     */
    int insert(PaymentErrorCodeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ERROR_CODE
     *
     * @mbggenerated Tue Sep 19 14:16:43 CST 2017
     */
    int insertSelective(PaymentErrorCodeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ERROR_CODE
     *
     * @mbggenerated Tue Sep 19 14:16:43 CST 2017
     */
    List<PaymentErrorCodeEntity> selectByExample(PaymentErrorCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ERROR_CODE
     *
     * @mbggenerated Tue Sep 19 14:16:43 CST 2017
     */
    PaymentErrorCodeEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ERROR_CODE
     *
     * @mbggenerated Tue Sep 19 14:16:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") PaymentErrorCodeEntity record, @Param("example") PaymentErrorCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ERROR_CODE
     *
     * @mbggenerated Tue Sep 19 14:16:43 CST 2017
     */
    int updateByExample(@Param("record") PaymentErrorCodeEntity record, @Param("example") PaymentErrorCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ERROR_CODE
     *
     * @mbggenerated Tue Sep 19 14:16:43 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentErrorCodeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ERROR_CODE
     *
     * @mbggenerated Tue Sep 19 14:16:43 CST 2017
     */
    int updateByPrimaryKey(PaymentErrorCodeEntity record);
}