package com.lanmao.data.sync.dao.entity;

public class PaymentRouterSubjectRuleEntityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.RULE_ID
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    private Long ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.SUBJECT_NO
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    private String subjectNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.PAY_WAY
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    private String payWay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.RULE_ID
     *
     * @return the value of LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.RULE_ID
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.RULE_ID
     *
     * @param ruleId the value for LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.RULE_ID
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.SUBJECT_NO
     *
     * @return the value of LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.SUBJECT_NO
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public String getSubjectNo() {
        return subjectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.SUBJECT_NO
     *
     * @param subjectNo the value for LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.SUBJECT_NO
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public void setSubjectNo(String subjectNo) {
        this.subjectNo = subjectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.PAY_WAY
     *
     * @return the value of LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.PAY_WAY
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public String getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.PAY_WAY
     *
     * @param payWay the value for LM_PAY.T_PAYMENT_ROUTER_SUBJECT_RULE.PAY_WAY
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }
}