package com.lanmao.data.sync.dao.entity;

public class PaymentSubjectChannelEntityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_PAYMENT_SUBJECT_CHANNEL.SUBJECT_NO
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    private String subjectNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_PAYMENT_SUBJECT_CHANNEL.CHANNEL_CONFIG_ID
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    private Long channelConfigId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_PAYMENT_SUBJECT_CHANNEL.SUBJECT_NO
     *
     * @return the value of LM_PAY.T_PAYMENT_SUBJECT_CHANNEL.SUBJECT_NO
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public String getSubjectNo() {
        return subjectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_PAYMENT_SUBJECT_CHANNEL.SUBJECT_NO
     *
     * @param subjectNo the value for LM_PAY.T_PAYMENT_SUBJECT_CHANNEL.SUBJECT_NO
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public void setSubjectNo(String subjectNo) {
        this.subjectNo = subjectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_PAYMENT_SUBJECT_CHANNEL.CHANNEL_CONFIG_ID
     *
     * @return the value of LM_PAY.T_PAYMENT_SUBJECT_CHANNEL.CHANNEL_CONFIG_ID
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public Long getChannelConfigId() {
        return channelConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_PAYMENT_SUBJECT_CHANNEL.CHANNEL_CONFIG_ID
     *
     * @param channelConfigId the value for LM_PAY.T_PAYMENT_SUBJECT_CHANNEL.CHANNEL_CONFIG_ID
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public void setChannelConfigId(Long channelConfigId) {
        this.channelConfigId = channelConfigId;
    }
}