package com.lanmao.data.sync.dao.entity;

public class PaymentRouterRuleChannelEntityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL.RULE_ID
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    private Long ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL.CHANNEL_NAME
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    private String channelName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL.RULE_ID
     *
     * @return the value of LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL.RULE_ID
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL.RULE_ID
     *
     * @param ruleId the value for LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL.RULE_ID
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL.CHANNEL_NAME
     *
     * @return the value of LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL.CHANNEL_NAME
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL.CHANNEL_NAME
     *
     * @param channelName the value for LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL.CHANNEL_NAME
     *
     * @mbggenerated Tue Aug 09 15:13:56 CST 2016
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }
}