package com.lanmao.data.sync.dao.db2;

import java.util.List;

import com.lanmao.data.sync.dao.entity.AuthRouterEntryEntity;
import com.lanmao.data.sync.dao.entity.AuthRouterEntryEntityExample;
import org.apache.ibatis.annotations.Param;

public interface AuthRouterEntryEntityMapper extends PageQueryMapper<AuthRouterEntryEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_ENTRY
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int countByExample(AuthRouterEntryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_ENTRY
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int deleteByExample(AuthRouterEntryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_ENTRY
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_ENTRY
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int insert(AuthRouterEntryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_ENTRY
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int insertSelective(AuthRouterEntryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_ENTRY
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    List<AuthRouterEntryEntity> selectByExample(AuthRouterEntryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_ENTRY
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    AuthRouterEntryEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_ENTRY
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") AuthRouterEntryEntity record, @Param("example") AuthRouterEntryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_ENTRY
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int updateByExample(@Param("record") AuthRouterEntryEntity record, @Param("example") AuthRouterEntryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_ENTRY
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int updateByPrimaryKeySelective(AuthRouterEntryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_ENTRY
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int updateByPrimaryKey(AuthRouterEntryEntity record);
}