package com.lanmao.data.sync.dao.db2;

import java.util.List;

import com.lanmao.data.sync.dao.entity.AuthRouterEntity;
import com.lanmao.data.sync.dao.entity.AuthRouterEntityExample;
import org.apache.ibatis.annotations.Param;

public interface AuthRouterEntityMapper extends PageQueryMapper<AuthRouterEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER
     *
     * @mbggenerated Mon Jan 22 09:32:37 CST 2018
     */
    int countByExample(AuthRouterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER
     *
     * @mbggenerated Mon Jan 22 09:32:37 CST 2018
     */
    int deleteByExample(AuthRouterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER
     *
     * @mbggenerated Mon Jan 22 09:32:37 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER
     *
     * @mbggenerated Mon Jan 22 09:32:37 CST 2018
     */
    int insert(AuthRouterEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER
     *
     * @mbggenerated Mon Jan 22 09:32:37 CST 2018
     */
    int insertSelective(AuthRouterEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER
     *
     * @mbggenerated Mon Jan 22 09:32:37 CST 2018
     */
    List<AuthRouterEntity> selectByExample(AuthRouterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER
     *
     * @mbggenerated Mon Jan 22 09:32:37 CST 2018
     */
    AuthRouterEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER
     *
     * @mbggenerated Mon Jan 22 09:32:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") AuthRouterEntity record, @Param("example") AuthRouterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER
     *
     * @mbggenerated Mon Jan 22 09:32:37 CST 2018
     */
    int updateByExample(@Param("record") AuthRouterEntity record, @Param("example") AuthRouterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER
     *
     * @mbggenerated Mon Jan 22 09:32:37 CST 2018
     */
    int updateByPrimaryKeySelective(AuthRouterEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER
     *
     * @mbggenerated Mon Jan 22 09:32:37 CST 2018
     */
    int updateByPrimaryKey(AuthRouterEntity record);
}