package com.lanmao.data.sync.dao.db2;

import java.util.List;

import com.lanmao.data.sync.dao.entity.AuthRouterSubjectEntity;
import com.lanmao.data.sync.dao.entity.AuthRouterSubjectEntityExample;
import org.apache.ibatis.annotations.Param;

public interface AuthRouterSubjectEntityMapper extends PageQueryMapper<AuthRouterSubjectEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_SUBJECT
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int countByExample(AuthRouterSubjectEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_SUBJECT
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int deleteByExample(AuthRouterSubjectEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_SUBJECT
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_SUBJECT
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int insert(AuthRouterSubjectEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_SUBJECT
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int insertSelective(AuthRouterSubjectEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_SUBJECT
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    List<AuthRouterSubjectEntity> selectByExample(AuthRouterSubjectEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_SUBJECT
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    AuthRouterSubjectEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_SUBJECT
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") AuthRouterSubjectEntity record, @Param("example") AuthRouterSubjectEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_SUBJECT
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int updateByExample(@Param("record") AuthRouterSubjectEntity record, @Param("example") AuthRouterSubjectEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_SUBJECT
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int updateByPrimaryKeySelective(AuthRouterSubjectEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ROUTER_SUBJECT
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int updateByPrimaryKey(AuthRouterSubjectEntity record);
}