package com.lanmao.data.sync.dao.db2;

import java.util.List;

import com.lanmao.data.sync.dao.entity.AuthErrorCodeEntity;
import com.lanmao.data.sync.dao.entity.AuthErrorCodeEntityExample;
import org.apache.ibatis.annotations.Param;

public interface AuthErrorCodeEntityMapper extends PageQueryMapper<AuthErrorCodeEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ERROR_CODE
     *
     * @mbggenerated Fri Aug 26 14:46:18 CST 2016
     */
    int countByExample(AuthErrorCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ERROR_CODE
     *
     * @mbggenerated Fri Aug 26 14:46:18 CST 2016
     */
    int deleteByExample(AuthErrorCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ERROR_CODE
     *
     * @mbggenerated Fri Aug 26 14:46:18 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ERROR_CODE
     *
     * @mbggenerated Fri Aug 26 14:46:18 CST 2016
     */
    int insert(AuthErrorCodeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ERROR_CODE
     *
     * @mbggenerated Fri Aug 26 14:46:18 CST 2016
     */
    int insertSelective(AuthErrorCodeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ERROR_CODE
     *
     * @mbggenerated Fri Aug 26 14:46:18 CST 2016
     */
    List<AuthErrorCodeEntity> selectByExample(AuthErrorCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ERROR_CODE
     *
     * @mbggenerated Fri Aug 26 14:46:18 CST 2016
     */
    AuthErrorCodeEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ERROR_CODE
     *
     * @mbggenerated Fri Aug 26 14:46:18 CST 2016
     */
    int updateByExampleSelective(@Param("record") AuthErrorCodeEntity record, @Param("example") AuthErrorCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ERROR_CODE
     *
     * @mbggenerated Fri Aug 26 14:46:18 CST 2016
     */
    int updateByExample(@Param("record") AuthErrorCodeEntity record, @Param("example") AuthErrorCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ERROR_CODE
     *
     * @mbggenerated Fri Aug 26 14:46:18 CST 2016
     */
    int updateByPrimaryKeySelective(AuthErrorCodeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_ERROR_CODE
     *
     * @mbggenerated Fri Aug 26 14:46:18 CST 2016
     */
    int updateByPrimaryKey(AuthErrorCodeEntity record);
}