package com.lanmao.data.sync.dao.db2;

import java.util.List;

import com.lanmao.data.sync.dao.entity.AuthMerchantAuthorizationEntity;
import com.lanmao.data.sync.dao.entity.AuthMerchantAuthorizationEntityExample;
import org.apache.ibatis.annotations.Param;

public interface AuthMerchantAuthorizationEntityMapper extends PageQueryMapper<AuthMerchantAuthorizationEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_MERCHANT_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int countByExample(AuthMerchantAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_MERCHANT_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int deleteByExample(AuthMerchantAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_MERCHANT_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_MERCHANT_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int insert(AuthMerchantAuthorizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_MERCHANT_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int insertSelective(AuthMerchantAuthorizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_MERCHANT_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    List<AuthMerchantAuthorizationEntity> selectByExample(AuthMerchantAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_MERCHANT_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    AuthMerchantAuthorizationEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_MERCHANT_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") AuthMerchantAuthorizationEntity record, @Param("example") AuthMerchantAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_MERCHANT_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int updateByExample(@Param("record") AuthMerchantAuthorizationEntity record, @Param("example") AuthMerchantAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_MERCHANT_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int updateByPrimaryKeySelective(AuthMerchantAuthorizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_AUTH_MERCHANT_AUTHORIZATION
     *
     * @mbggenerated Thu Dec 08 13:42:16 CST 2016
     */
    int updateByPrimaryKey(AuthMerchantAuthorizationEntity record);
}