package com.lanmao.data.sync.dao.db2;

import com.lanmao.data.sync.dao.entity.CertRecordEntity;
import com.lanmao.data.sync.dao.entity.CertRecordEntityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CertRecordEntityMapper extends PageQueryMapper<CertRecordEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_CERT_RECORD
     *
     * @mbggenerated Wed Oct 25 16:45:43 CST 2017
     */
    int countByExample(CertRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_CERT_RECORD
     *
     * @mbggenerated Wed Oct 25 16:45:43 CST 2017
     */
    int deleteByExample(CertRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_CERT_RECORD
     *
     * @mbggenerated Wed Oct 25 16:45:43 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_CERT_RECORD
     *
     * @mbggenerated Wed Oct 25 16:45:43 CST 2017
     */
    int insert(CertRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_CERT_RECORD
     *
     * @mbggenerated Wed Oct 25 16:45:43 CST 2017
     */
    int insertSelective(CertRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_CERT_RECORD
     *
     * @mbggenerated Wed Oct 25 16:45:43 CST 2017
     */
    List<CertRecordEntity> selectByExample(CertRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_CERT_RECORD
     *
     * @mbggenerated Wed Oct 25 16:45:43 CST 2017
     */
    CertRecordEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_CERT_RECORD
     *
     * @mbggenerated Wed Oct 25 16:45:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") CertRecordEntity record, @Param("example") CertRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_CERT_RECORD
     *
     * @mbggenerated Wed Oct 25 16:45:43 CST 2017
     */
    int updateByExample(@Param("record") CertRecordEntity record, @Param("example") CertRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_CERT_RECORD
     *
     * @mbggenerated Wed Oct 25 16:45:43 CST 2017
     */
    int updateByPrimaryKeySelective(CertRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_CERT_RECORD
     *
     * @mbggenerated Wed Oct 25 16:45:43 CST 2017
     */
    int updateByPrimaryKey(CertRecordEntity record);
}