package com.lanmao.data.sync.dao.db2;


import java.util.List;

import com.lanmao.data.sync.dao.entity.PaymentOrderEntity;
import com.lanmao.data.sync.dao.entity.PaymentOrderEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PaymentOrderEntityMapper extends PageQueryMapper<PaymentOrderEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER
     *
     * @mbggenerated Tue Jan 30 12:50:03 CST 2018
     */
    int countByExample(PaymentOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER
     *
     * @mbggenerated Tue Jan 30 12:50:03 CST 2018
     */
    int deleteByExample(PaymentOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER
     *
     * @mbggenerated Tue Jan 30 12:50:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER
     *
     * @mbggenerated Tue Jan 30 12:50:03 CST 2018
     */
    int insert(PaymentOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER
     *
     * @mbggenerated Tue Jan 30 12:50:03 CST 2018
     */
    int insertSelective(PaymentOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER
     *
     * @mbggenerated Tue Jan 30 12:50:03 CST 2018
     */
    List<PaymentOrderEntity> selectByExample(PaymentOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER
     *
     * @mbggenerated Tue Jan 30 12:50:03 CST 2018
     */
    PaymentOrderEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER
     *
     * @mbggenerated Tue Jan 30 12:50:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") PaymentOrderEntity record, @Param("example") PaymentOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER
     *
     * @mbggenerated Tue Jan 30 12:50:03 CST 2018
     */
    int updateByExample(@Param("record") PaymentOrderEntity record, @Param("example") PaymentOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER
     *
     * @mbggenerated Tue Jan 30 12:50:03 CST 2018
     */
    int updateByPrimaryKeySelective(PaymentOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ORDER
     *
     * @mbggenerated Tue Jan 30 12:50:03 CST 2018
     */
    int updateByPrimaryKey(PaymentOrderEntity record);

}