package com.lanmao.data.sync.dao.db2;

import java.util.List;

import com.lanmao.data.sync.dao.entity.PaymentProfitMonthlyEntity;
import com.lanmao.data.sync.dao.entity.PaymentProfitMonthlyEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PaymentProfitMonthlyEntityMapper extends PageQueryMapper<PaymentProfitMonthlyEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_MONTHLY
     *
     * @mbggenerated Wed Oct 11 15:40:52 CST 2017
     */
    int countByExample(PaymentProfitMonthlyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_MONTHLY
     *
     * @mbggenerated Wed Oct 11 15:40:52 CST 2017
     */
    int deleteByExample(PaymentProfitMonthlyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_MONTHLY
     *
     * @mbggenerated Wed Oct 11 15:40:52 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_MONTHLY
     *
     * @mbggenerated Wed Oct 11 15:40:52 CST 2017
     */
    int insert(PaymentProfitMonthlyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_MONTHLY
     *
     * @mbggenerated Wed Oct 11 15:40:52 CST 2017
     */
    int insertSelective(PaymentProfitMonthlyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_MONTHLY
     *
     * @mbggenerated Wed Oct 11 15:40:52 CST 2017
     */
    List<PaymentProfitMonthlyEntity> selectByExample(PaymentProfitMonthlyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_MONTHLY
     *
     * @mbggenerated Wed Oct 11 15:40:52 CST 2017
     */
    PaymentProfitMonthlyEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_MONTHLY
     *
     * @mbggenerated Wed Oct 11 15:40:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") PaymentProfitMonthlyEntity record, @Param("example") PaymentProfitMonthlyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_MONTHLY
     *
     * @mbggenerated Wed Oct 11 15:40:52 CST 2017
     */
    int updateByExample(@Param("record") PaymentProfitMonthlyEntity record, @Param("example") PaymentProfitMonthlyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_MONTHLY
     *
     * @mbggenerated Wed Oct 11 15:40:52 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentProfitMonthlyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_PROFIT_MONTHLY
     *
     * @mbggenerated Wed Oct 11 15:40:52 CST 2017
     */
    int updateByPrimaryKey(PaymentProfitMonthlyEntity record);
    /**
     * 批量插入月总计
     * @param list
     * @return
     */
    int batchInsert(List<PaymentProfitMonthlyEntity> list);
}