package com.lanmao.data.sync.dao.db2;

import com.lanmao.data.sync.dao.entity.PaymentChannelConfigEntity;
import com.lanmao.data.sync.dao.entity.PaymentChannelConfigEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentChannelConfigEntityMapper extends PageQueryMapper<PaymentChannelConfigEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 29 16:38:31 CST 2017
     */
    int countByExample(PaymentChannelConfigEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 29 16:38:31 CST 2017
     */
    int deleteByExample(PaymentChannelConfigEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 29 16:38:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 29 16:38:31 CST 2017
     */
    int insert(PaymentChannelConfigEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 29 16:38:31 CST 2017
     */
    int insertSelective(PaymentChannelConfigEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 29 16:38:31 CST 2017
     */
    List<PaymentChannelConfigEntity> selectByExample(PaymentChannelConfigEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 29 16:38:31 CST 2017
     */
    PaymentChannelConfigEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 29 16:38:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") PaymentChannelConfigEntity record, @Param("example") PaymentChannelConfigEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 29 16:38:31 CST 2017
     */
    int updateByExample(@Param("record") PaymentChannelConfigEntity record, @Param("example") PaymentChannelConfigEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 29 16:38:31 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentChannelConfigEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHANNEL_CONFIG
     *
     * @mbggenerated Tue Aug 29 16:38:31 CST 2017
     */
    int updateByPrimaryKey(PaymentChannelConfigEntity record);
}