package com.lanmao.data.sync.dao.db2;

import com.lanmao.data.sync.dao.entity.PaymentLogEntity;
import com.lanmao.data.sync.dao.entity.PaymentLogEntityExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PaymentLogEntityMapper extends PageQueryMapper<PaymentLogEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_LOG
     *
     * @mbggenerated Fri Aug 11 16:54:35 CST 2017
     */
    int countByExample(PaymentLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_LOG
     *
     * @mbggenerated Fri Aug 11 16:54:35 CST 2017
     */
    int deleteByExample(PaymentLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_LOG
     *
     * @mbggenerated Fri Aug 11 16:54:35 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_LOG
     *
     * @mbggenerated Fri Aug 11 16:54:35 CST 2017
     */
    int insert(PaymentLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_LOG
     *
     * @mbggenerated Fri Aug 11 16:54:35 CST 2017
     */
    int insertSelective(PaymentLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_LOG
     *
     * @mbggenerated Fri Aug 11 16:54:35 CST 2017
     */
    List<PaymentLogEntity> selectByExample(PaymentLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_LOG
     *
     * @mbggenerated Fri Aug 11 16:54:35 CST 2017
     */
    PaymentLogEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_LOG
     *
     * @mbggenerated Fri Aug 11 16:54:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") PaymentLogEntity record, @Param("example") PaymentLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_LOG
     *
     * @mbggenerated Fri Aug 11 16:54:35 CST 2017
     */
    int updateByExample(@Param("record") PaymentLogEntity record, @Param("example") PaymentLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_LOG
     *
     * @mbggenerated Fri Aug 11 16:54:35 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_LOG
     *
     * @mbggenerated Fri Aug 11 16:54:35 CST 2017
     */
    int updateByPrimaryKey(PaymentLogEntity record);
    
    int deleteByTimeAndRow(@Param("createTime") Date createTime, @Param("rowNum") int rowNum);
}