package com.lanmao.data.sync.dao.db2;

import java.util.List;

import com.lanmao.data.sync.dao.entity.PaymentAuthorizationEntity;
import com.lanmao.data.sync.dao.entity.PaymentAuthorizationEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PaymentAuthorizationEntityMapper extends PageQueryMapper<PaymentAuthorizationEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_AUTHORIZATION
     *
     * @mbggenerated Sat May 27 16:49:25 CST 2017
     */
    int countByExample(PaymentAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_AUTHORIZATION
     *
     * @mbggenerated Sat May 27 16:49:25 CST 2017
     */
    int deleteByExample(PaymentAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_AUTHORIZATION
     *
     * @mbggenerated Sat May 27 16:49:25 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_AUTHORIZATION
     *
     * @mbggenerated Sat May 27 16:49:25 CST 2017
     */
    int insert(PaymentAuthorizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_AUTHORIZATION
     *
     * @mbggenerated Sat May 27 16:49:25 CST 2017
     */
    int insertSelective(PaymentAuthorizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_AUTHORIZATION
     *
     * @mbggenerated Sat May 27 16:49:25 CST 2017
     */
    List<PaymentAuthorizationEntity> selectByExample(PaymentAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_AUTHORIZATION
     *
     * @mbggenerated Sat May 27 16:49:25 CST 2017
     */
    PaymentAuthorizationEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_AUTHORIZATION
     *
     * @mbggenerated Sat May 27 16:49:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") PaymentAuthorizationEntity record, @Param("example") PaymentAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_AUTHORIZATION
     *
     * @mbggenerated Sat May 27 16:49:25 CST 2017
     */
    int updateByExample(@Param("record") PaymentAuthorizationEntity record, @Param("example") PaymentAuthorizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_AUTHORIZATION
     *
     * @mbggenerated Sat May 27 16:49:25 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentAuthorizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_AUTHORIZATION
     *
     * @mbggenerated Sat May 27 16:49:25 CST 2017
     */
    int updateByPrimaryKey(PaymentAuthorizationEntity record);
}