package com.lanmao.data.sync.dao.db2;

import java.util.List;

import com.lanmao.data.sync.dao.entity.PaymentCheckAccountEntity;
import com.lanmao.data.sync.dao.entity.PaymentCheckAccountEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PaymentCheckAccountEntityMapper extends PageQueryMapper<PaymentCheckAccountEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHECK_ACCOUNT
     *
     * @mbggenerated Wed Sep 13 16:59:51 CST 2017
     */
    int countByExample(PaymentCheckAccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHECK_ACCOUNT
     *
     * @mbggenerated Wed Sep 13 16:59:51 CST 2017
     */
    int deleteByExample(PaymentCheckAccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHECK_ACCOUNT
     *
     * @mbggenerated Wed Sep 13 16:59:51 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHECK_ACCOUNT
     *
     * @mbggenerated Wed Sep 13 16:59:51 CST 2017
     */
    int insert(PaymentCheckAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHECK_ACCOUNT
     *
     * @mbggenerated Wed Sep 13 16:59:51 CST 2017
     */
    int insertSelective(PaymentCheckAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHECK_ACCOUNT
     *
     * @mbggenerated Wed Sep 13 16:59:51 CST 2017
     */
    List<PaymentCheckAccountEntity> selectByExample(PaymentCheckAccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHECK_ACCOUNT
     *
     * @mbggenerated Wed Sep 13 16:59:51 CST 2017
     */
    PaymentCheckAccountEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHECK_ACCOUNT
     *
     * @mbggenerated Wed Sep 13 16:59:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") PaymentCheckAccountEntity record, @Param("example") PaymentCheckAccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHECK_ACCOUNT
     *
     * @mbggenerated Wed Sep 13 16:59:51 CST 2017
     */
    int updateByExample(@Param("record") PaymentCheckAccountEntity record, @Param("example") PaymentCheckAccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHECK_ACCOUNT
     *
     * @mbggenerated Wed Sep 13 16:59:51 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentCheckAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_CHECK_ACCOUNT
     *
     * @mbggenerated Wed Sep 13 16:59:51 CST 2017
     */
    int updateByPrimaryKey(PaymentCheckAccountEntity record);
}