package com.lanmao.data.sync.dao.db2;

import java.util.List;

import com.lanmao.data.sync.dao.entity.PaymentRouterRuleChannelEntity;
import com.lanmao.data.sync.dao.entity.PaymentRouteRuleChannelEntityExample;
import com.lanmao.data.sync.dao.entity.PaymentRouterRuleChannelEntityKey;
import org.apache.ibatis.annotations.Param;

public interface PaymentRouterRuleChannelEntityMapper extends PageQueryMapper<PaymentRouterRuleChannelEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL
     *
     * @mbggenerated Thu Apr 07 16:26:01 CST 2016
     */
    int countByExample(PaymentRouteRuleChannelEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL
     *
     * @mbggenerated Thu Apr 07 16:26:01 CST 2016
     */
    int deleteByExample(PaymentRouteRuleChannelEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL
     *
     * @mbggenerated Thu Apr 07 16:26:01 CST 2016
     */
    int deleteByPrimaryKey(PaymentRouterRuleChannelEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL
     *
     * @mbggenerated Thu Apr 07 16:26:01 CST 2016
     */
    int insert(PaymentRouterRuleChannelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL
     *
     * @mbggenerated Thu Apr 07 16:26:01 CST 2016
     */
    int insertSelective(PaymentRouterRuleChannelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL
     *
     * @mbggenerated Thu Apr 07 16:26:01 CST 2016
     */
    List<PaymentRouterRuleChannelEntity> selectByExample(PaymentRouteRuleChannelEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL
     *
     * @mbggenerated Thu Apr 07 16:26:01 CST 2016
     */
    PaymentRouterRuleChannelEntity selectByPrimaryKey(PaymentRouterRuleChannelEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL
     *
     * @mbggenerated Thu Apr 07 16:26:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") PaymentRouterRuleChannelEntity record, @Param("example") PaymentRouteRuleChannelEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL
     *
     * @mbggenerated Thu Apr 07 16:26:01 CST 2016
     */
    int updateByExample(@Param("record") PaymentRouterRuleChannelEntity record, @Param("example") PaymentRouteRuleChannelEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL
     *
     * @mbggenerated Thu Apr 07 16:26:01 CST 2016
     */
    int updateByPrimaryKeySelective(PaymentRouterRuleChannelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE_CHANNEL
     *
     * @mbggenerated Thu Apr 07 16:26:01 CST 2016
     */
    int updateByPrimaryKey(PaymentRouterRuleChannelEntity record);
}