package com.lanmao.data.sync.dao.db2;

import java.util.List;

import com.lanmao.data.sync.dao.entity.PaymentRouterRuleEntity;
import com.lanmao.data.sync.dao.entity.PaymentRouteRuleEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PaymentRouterRuleEntityMapper extends PageQueryMapper<PaymentRouterRuleEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int countByExample(PaymentRouteRuleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int deleteByExample(PaymentRouteRuleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int insert(PaymentRouterRuleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int insertSelective(PaymentRouterRuleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    List<PaymentRouterRuleEntity> selectByExample(PaymentRouteRuleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    PaymentRouterRuleEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") PaymentRouterRuleEntity record, @Param("example") PaymentRouteRuleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int updateByExample(@Param("record") PaymentRouterRuleEntity record, @Param("example") PaymentRouteRuleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int updateByPrimaryKeySelective(PaymentRouterRuleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LM_PAY.T_PAYMENT_ROUTER_RULE
     *
     * @mbggenerated Thu Apr 07 14:41:04 CST 2016
     */
    int updateByPrimaryKey(PaymentRouterRuleEntity record);
}